name: secrets

on:
  # Trigger the workflow on push
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: List S3 Buckets
      run: aws s3api list-buckets
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: List files
      run: ls -l
    - name: Zip script
      run: "zip ./test-ft.zip new-lambda.py"
    - name: Upload to AWS 
      run: aws lambda update-function-code --function-name test-1 --zip-file fileb://test-ft.zip
