name: secrets

on:
  # Trigger the workflow on push
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: Zip script
      run: "zip ./test-ft.zip lambda_function.py"
    - name: Upload to AWS 
      run: aws lambda update-function-code --function-name test-2 --zip-file fileb://test-ft.zip —description version-$(date +%Y%m%d-%H%M%S)
    - name: Get the latest version (Which is in DEV)
      run: LATEST_VERSION=$(aws lambda list-versions-by-function —function-name test-2 —query “max_by(Versions, &Version).{Version:Version}” | grep “Version” | cut -d”:” -f2 | cut -d’”’ -f2) 
    - name: Repoint dev alias to the uploaded version
      run: aws lambda update-alias —function-name test-2  —name dev —function-version $LATEST_VERSION
    - name: Run a test on the dev alias
      run: "aws lambda invoke —cli-binary-format raw-in-base64-out —function-name test-2:dev —payload ‘{ “name”: “Bob” }’ response.json"



